# ===================== PL/0 语法规则（LL(1) 修正版） =====================

<program> ::= <decl_part> <compound_stmt> DOT


# ---------- 声明部分（显式拆分，解决 program 起始冲突） ----------

<decl_part> ::= <const_decl_part> <var_decl_part> <proc_decl_part>
              | <var_decl_part> <proc_decl_part>
              | <proc_decl_part>
              | ε


<const_decl_part> ::= CONST <const_list> SEMI

<const_list> ::= IDENTIFIER EQ NUMBER <const_list_tail>

<const_list_tail> ::= COMMA IDENTIFIER EQ NUMBER <const_list_tail>
                    | ε


<var_decl_part> ::= VAR <ident_list> SEMI

<ident_list> ::= IDENTIFIER <ident_list_rest>

<ident_list_rest> ::= COMMA IDENTIFIER <ident_list_rest>
                    | ε


<proc_decl_part> ::= <proc_decl> <proc_decl_part>
                   | ε

<proc_decl> ::= PROCEDURE IDENTIFIER SEMI <program> SEMI


# ---------- 语句部分 ----------

<compound_stmt> ::= BEGIN <stmt_list> END

<stmt_list> ::= <stmt> <stmt_list_tail>

<stmt_list_tail> ::= SEMI <stmt> <stmt_list_tail>
                   | ε


<stmt> ::= <assign_stmt>
         | <if_stmt>
         | <while_stmt>
         | <call_stmt>
         | <compound_stmt>
         | ε


<assign_stmt> ::= IDENTIFIER ASSIGN <expr>

<call_stmt> ::= CALL IDENTIFIER

<if_stmt> ::= IF <condition> THEN <stmt>

<while_stmt> ::= WHILE <condition> DO <stmt>


# ---------- 表达式 ----------

<condition> ::= ODD <expr>
              | <expr> <relop> <expr>

<relop> ::= EQ | NE | LT | GT | LE | GE


<expr> ::= <term> <expr_tail>

<expr_tail> ::= PLUS <term> <expr_tail>
              | MINUS <term> <expr_tail>
              | ε


<term> ::= <factor> <term_tail>

<term_tail> ::= MULT <factor> <term_tail>
              | DIV <factor> <term_tail>
              | ε


<factor> ::= IDENTIFIER
           | NUMBER
           | LPAREN <expr> RPAREN
